apiVersion: v1
kind: ConfigMap
metadata:
  namespace: swcaptest
  name: capaggregator
data:
  RABBIT_HOST: "default-rabbit-rabbitmq.services"
  CAP_RABBIT_USER: "cap"
  CAP_RABBIT_PASS: "CAP_USER_PASSWORD"
  CC_DB_URL: "jdbc:postgresql://pg12-postgresql.default:5432/capcollator"
  CC_USERNAME: "capcollator"
  CC_PASSWORD: "CC_DB_PASSWORD"
  CC_JDBC_DRIVER: "org.postgresql.Driver"
  CC_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  CC_ES_HOST: "elasticsearch-coordinating-only.services"

