apiVersion: v1
kind: PersistentVolume
metadata:
  name: cc-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: cc-pvc
    namespace: swcaptest
spec:
    accessModes:
      - ReadWriteMany
    storageClassName: hostpath
    resources:
        requests:
            storage: 1Gi
